obj-m += zfq-iosched.o

all:
	make -C /lib/modules/4.8.8JiananYang+/build M=/home/jianan/asu/cs/cse330/project/CSE330Project/p5 modules

clean:
	make -C /lib/modules/4.8.8JiananYang+/build M=/home/jianan/asu/cs/cse330/project/CSE330Project/p5 clean
